services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wellcare-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword@123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - db

    volumes:
      - ./docker/init.sql:/init.sql
    command: >
      bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P StrongPassword@123 -C -d master -i /init.sql
      "

  web:
    build:
      context: ./wellcare
    container_name: wellcare-web
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Server=db;
        Database=wellcare;
        User Id=sa;
        Password=StrongPassword@123;
        TrustServerCertificate=True;

volumes:
  sql_data:
